--SQL Queries

--1
SELECT DISTINCT CITY
    FROM CUSTOMER
    ORDER BY CITY;

--2
SELECT TITLE, PRICE
    FROM ITEM
    WHERE TYPE = 'DVD'
    ORDER BY PRICE;

--3
SELECT TITLE, TYPE, PRICE
    FROM ITEM
    WHERE PRICE < 15
    ORDER BY PRICE DESC;

--4
SELECT TITLE
    FROM ITEM
    WHERE TITLE LIKE '%West%'
    ORDER BY TITLE;

--5
SELECT CID
  FROM PURCHASE
  WHERE PDATE LIKE '__-___-19'
  ORDER BY CID;

--6
SELECT CID, MAX(PDATE)
  FROM PURCHASE
  GROUP BY CID;

--7
SELECT TYPE, MIN(PRICE)
  FROM ITEM
  GROUP BY TYPE;

--8
SELECT PDATE, COUNT(PDATE)
  FROM PURCHASE
  GROUP BY PDATE
  ORDER BY COUNT(PDATE) DESC;

--9
SELECT PID, PDATE
  FROM (CUSTOMER INNER JOIN PURCHASE ON ID = CID)
  WHERE NAME = 'Reed';

--10
SELECT PID, SUM(PRICE * QUANTITY)
  FROM (PURCHASE INNER JOIN ITEM ON IID = ID)
  GROUP BY PID
  ORDER BY SUM(PRICE * QUANTITY) DESC;
