--1
SELECT ENAME, SAL, EMP.DEPTNO
    FROM EMP FULL OUTER JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
    WHERE COMM IS NULL AND SAL < 2000;

--2
SELECT ENAME, SAL, MGR
    FROM EMP a, EMP b
    WHERE DEPTNO = 20;

--3
SELECT DEPARTMENTS.DEPARTMENT_ID, departments.department_name, COUNT(DEPARTMENTS.DEPARTMENT_ID)
    FROM EMPLOYEES INNER JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
    GROUP BY DEPARTMENTS.DEPARTMENT_ID, DEPARTMENT_NAME;

--4
SELECT DEPARTMENTS.DEPARTMENT_ID, departments.department_name
    FROM EMPLOYEES FULL OUTER JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
    WHERE (SELECT * FROM DEPARTMENTS WHERE COUNT(EMPLOYEES.EMPLOYEE_ID) = 0;)

--5
SELECT FIRST_NAME, LAST_NAME, MANAGER_ID
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID IS NULL;

--6
SELECT MAX(SALARY + SALARY * NVL(commission_pct, 0)), MIN(SALARY + SALARY * NVL(commission_pct, 0))
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID;

--7
SELECT EMPLOYEE_ID, LAST_NAME, FIRST_NAME, DEPARTMENT_ID
    FROM EMPLOYEES
    WHERE LAST_NAME IN (SELECT LAST_NAME FROM EMPLOYEES GROUP BY LAST_NAME HAVING COUNT(*) > 1);

--8
SELECT PHONE_NUMBER
    FROM EMPLOYEES
    WHERE SUBSTR(PHONE_NUMBER, 1, 3) = '011';

--9
SELECT table_name
    FROM USER_TABLES;

--10
DECLARE
    emp_name VARCHAR2(15);

BEGIN
    SELECT ename INTO emp_name
    FROM EMP
    WHERE empno = '7839';

DBMS_OUTPUT.PUT_LINE(emp_name);
END;
/
